-- Migrasi 008 (rich profile + orbs + status)
USE nobarly;

ALTER TABLE profiles ADD COLUMN IF NOT EXISTS bio VARCHAR(280);
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS orbs INT DEFAULT 0;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS avatar_frame VARCHAR(24);
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS banner VARCHAR(24);
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS server_tag VARCHAR(24);
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS status VARCHAR(12) DEFAULT 'online';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS connections TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS last_checkin DATE;
